### ISSUE TITLE
Unable to boot to lede

### ISSUE THREAD

**Issue by andreacampanella** [mkresin/lede#2] opened 2018-04-07 17:19 UTC
I tried to install the latest LEDE , now , If I boot I get : 

U-Boot 2010.06-LANTIQ-v-2.2.46 (Dec 06 2013 - 02:39:45 on tester@clean-machine)

CLOCK CPU 500M RAM 250M
secure boot
DRAM:  125 MiB
NAND:  ONFI flash detected
ONFI param page 0 valid
NAND device: Manufacturer ID: 0x01, Chip ID: 0xf1 (AMD S34ML01G1)
128 MiB
Bad block table found at page 65472, version 0x01
Bad block table found at page 65408, version 0x01
In:    serial
Out:   serial
Err:   serial
Net:   Internal phy(GE) firmware version: 0x841b
vr9 Switch

Type "run flash_nfs" to mount root filesystem over NFS

Hit any key to stop autoboot:  0 
Creating 1 MTD partitions on "nand0":
0x000000100000-0x000007f80000 : "mtd=0"
UBI: attaching mtd1 to ubi0
UBI: physical eraseblock size:   131072 bytes (128 KiB)
UBI: logical eraseblock size:    129024 bytes
UBI: smallest flash I/O unit:    2048
UBI: sub-page size:              512
UBI: VID header offset:          512 (aligned 512)
UBI: data offset:                2048
UBI: attached mtd1 to ubi0
UBI: MTD device name:            "mtd=0"
UBI: MTD device size:            126 MiB
UBI: number of good PEBs:        1012
UBI: number of bad PEBs:         0
UBI: max. allowed volumes:       128
UBI: wear-leveling threshold:    4096
UBI: number of internal volumes: 1
UBI: number of user volumes:     3
UBI: available PEBs:             9
UBI: total number of reserved PEBs: 1003
UBI: number of PEBs reserved for bad PEB handling: 10
UBI: max/mean erase counter: 84/57
kernel volume not found
Wrong Image Format for bootm command
ERROR: can't get kernel image!
VR9 # 
I tried to restore from a backup but that didn't lead at anything useful , I'm stuck here and if I try to tftpboot and launch a "prepare" I get : 

"error bootcmd_openrg already exists" 

my u-boot and env : 

[u-boot.zip](https://github.com/mkresin/BTHH5a-installimage/files/1886592/u-boot.zip)

**Comment by mkresin** [comment] 2018-09-06 19:04
duplicate of #4

**Closed as completed by mkresin** 2018-09-06 19:04 UTC
